/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rest.assured.api.automation.tests

import io.restassured.RestAssured.*
import kotlin.test.Test
import io.restassured.http.ContentType
import org.apache.http.HttpStatus
import org.hamcrest.CoreMatchers.`is`
import org.hamcrest.CoreMatchers.notNullValue
import rest.assured.api.automation.domain.User

class UserTests: BaseTest() {

    @Test
    fun testListUserMetadata() {
        given().
            params("page", "2").
        `when`().
                get("/users").
         then().
                statusCode(HttpStatus.SC_OK).
                body("page", `is`(2)).
                body("data", `is`(notNullValue()))
    }

    @Test
    fun testCreateUser() {
        val user = User("Fabio", "Test Engineer")
        given().
            contentType(ContentType.JSON).
            body(user).
        `when`().
            post("/users").
        then().
            statusCode(HttpStatus.SC_CREATED).
            body("name", `is`("Fabio"))
    }
}
