/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rest.assured.api.automation.tests

import io.restassured.RestAssured.*
import kotlin.test.Test
import org.apache.http.HttpStatus
import org.hamcrest.CoreMatchers.`is`
import org.hamcrest.CoreMatchers.notNullValue
import rest.assured.api.automation.domain.User

class UserTests: BaseTest() {

    companion object {
        private const val USERS_LIST_ENDPOINT: String = "/users"
        private const val CREATE_USER_ENDPOINT: String = "/user"
    }

    @Test
    fun testListUserMetadata() {
        given().
            params("page", "2").
        `when`().
                get(USERS_LIST_ENDPOINT).
         then().
                statusCode(HttpStatus.SC_OK).
                body("page", `is`(2)).
                body("data", `is`(notNullValue()))
    }

    @Test
    fun testCreateUser() {
        val user = User("Fabio", "Test Engineer")
        given().
            body(user).
        `when`().
            post(CREATE_USER_ENDPOINT).
        then().
            statusCode(HttpStatus.SC_CREATED).
            body("name", `is`("Fabio"))
    }

    @Test
    fun testCheckShownItemsAreTheSameAsItemsPerPage() {
        given().
            params("page", "2").
        `when`().
            get(USERS_LIST_ENDPOINT).
        then().
            statusCode(HttpStatus.SC_OK).
            body(
                    "page", `is`(2),
                    "data.size()", `is`(6),
                    "data.findAll { it.avatar.startsWith('https://reqres.in/img/faces') }.size()", `is`(6)
            )
    }
}
