/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rest.assured.api.automation

import kotlin.test.Test
import io.restassured.RestAssured.`when`
import io.restassured.RestAssured.given
import io.restassured.http.ContentType
import org.apache.http.HttpStatus
import org.hamcrest.CoreMatchers.`is`
import org.hamcrest.CoreMatchers.notNullValue

class AppTest {

    @Test
    fun testListUserMetadata() {
        `when`().
                get("https://reqres.in/api/users?page=2").
         then().
                statusCode(HttpStatus.SC_OK).
                body("page", `is`(2)).
                body("data", `is`(notNullValue()))
    }

    @Test
    fun testCreateUser() {
        given().log().all().
            contentType(ContentType.JSON).
            body("{\"name\": \"Fabio\", \"job\": \"Test Engineer\"}").
        `when`().
            post("https://reqres.in/api/users").
        then().
            statusCode(HttpStatus.SC_CREATED).
            body("name", `is`("Fabio"))
    }
}
